Added GitHub Actions

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -1,97 +1,37 @@
 on: pull_request
-name: PR Review
+name: Review
 jobs:
-  test-composer-files:
-    name: Validate composer
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        php-versions: [ '8.1' ]
-    steps:
-      - uses: actions/checkout@master
-      - name: Setup PHP, with composer and extensions
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: ${{ matrix.php-versions }}
-          extensions: json
-          coverage: none
-          tools: composer:v2
-      # https://github.com/shivammathur/setup-php#cache-composer-dependencies
-      - name: Get composer cache directory
-        id: composer-cache
-        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
-      - name: Cache dependencies
-        uses: actions/cache@v2
-        with:
-          path: ${{ steps.composer-cache.outputs.dir }}
-          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
-          restore-keys: ${{ runner.os }}-composer-
-      - name: Validate composer files
-        run: |
-          composer validate --strict composer.json
-          # Check that dependencies resolve.
-          composer update --prefer-dist --no-interaction
+  # changelog:
+  #   runs-on: ubuntu-latest
+  #   name: Changelog should be updated
+  #   strategy:
+  #     fail-fast: false
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 2
 
-  php-check-coding-standards:
-    name: PHP - Check Coding Standards
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        php-versions: [ '8.1' ]
-    steps:
-      - uses: actions/checkout@master
-      - name: Setup PHP, with composer and extensions
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: ${{ matrix.php-versions }}
-          extensions: json
-          coverage: none
-          tools: composer:v2
-      # https://github.com/shivammathur/setup-php#cache-composer-dependencies
-      - name: Get composer cache directory
-        id: composer-cache
-        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
-      - name: Cache dependencies
-        uses: actions/cache@v2
-        with:
-          path: ${{ steps.composer-cache.outputs.dir }}
-          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
-          restore-keys: ${{ runner.os }}-composer-
-      - name: Install Dependencies
-        run: |
-          composer install --no-interaction --no-progress
-      - name: PHPCS
-        run: |
-          composer coding-standards-check
+  #     - name: Git fetch
+  #       run: git fetch
 
-  php-code-analysis:
-    name: PHP - Code analysis
-    runs-on: ubuntu-latest
+  #     - name: Check that changelog has been updated.
+  #       run: git diff --exit-code origin/${{ github.base_ref }} -- CHANGELOG.md && exit 1 || exit 0
+
+  translations:
+    runs-on: ubuntu-20.04
     strategy:
+      fail-fast: false
       matrix:
-        php-versions: [ '8.1' ]
+        php: [ '8.1' ]
+    name: Check translations are up to date (${{ matrix.php}})
     steps:
-      - uses: actions/checkout@master
-      - name: Setup PHP, with composer and extensions
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: ${{ matrix.php-versions }}
-          extensions: json, gd
-          coverage: none
-          tools: composer:v2
-      # https://github.com/shivammathur/setup-php#cache-composer-dependencies
-      - name: Get composer cache directory
-        id: composer-cache
-        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
-      - name: Cache dependencies
-        uses: actions/cache@v2
-        with:
-          path: ${{ steps.composer-cache.outputs.dir }}
-          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
-          restore-keys: ${{ runner.os }}-composer-
-      - name: Install Dependencies
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Update translations
         run: |
-          composer install --no-interaction --no-progress
-      - name: Code analysis
+          docker compose run --rm phpfpm composer install --no-scripts
+          docker compose run --rm phpfpm composer update-translations
+      - name: Check for changes in translation files
         run: |
-          composer code-analysis
+          git diff --diff-filter=ACMRT --exit-code translations
